source 'https://rubygems.org'

gem 'rails',                      '4.1.5'
gem 'angularjs-rails',            '~> 1.2.20'
gem 'angular-ui-bootstrap-rails', '~> 0.11.0'
gem 'cancancan',                  '~> 1.9'
gem 'capistrano-rails',           '~> 1.1.1'
gem 'compass-rails',              '~> 2.0.0'
gem 'bcrypt',                     '~> 3.1.7'
gem 'bootstrap-sass',             '~> 3.1.1'
gem 'coffee-rails',               '~> 4.0.0'
gem 'devise',                     '~> 3.2.4'
gem 'font-awesome-rails',         '~> 4.2.0.0'
gem 'jbuilder',                   '~> 2.0'
gem 'jquery-rails',               '~> 3.1.0'
gem 'kaminari',                   '~> 0.16.1'
gem 'mysql2',                     '~> 0.3.16'
gem 'pnotify-rails',              '~> 2.0.1.1'
gem 'ranked-model',               '~> 0.4.0'
gem 'rolify',                     '~> 3.4.0'
gem 'rspec',                      '~> 3.0.0'
gem 'rspec-rails',                '~> 3.0.1'
gem 'sass-rails',                 '~> 4.0.3'
gem 'settingslogic',              '~> 2.0.9'
gem 'therubyracer',               '~> 0.12.1', platforms: :ruby
gem 'uglifier',                   '~> 1.3.0'
gem 'unicorn',                    '~> 4.8.3'

group :doc do
  gem 'sdoc'
end

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rack-mini-profiler'
  gem 'rubocop'
  gem 'spring'
  gem 'thin'
  gem 'hirb'
  gem 'hirb-unicode'
end
